# Generated by Django 6.0.2 on 2026-03-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('youtube_url', models.URLField()),
                ('level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('PROFESSIONAL', 'Professional')], max_length=20)),
                ('q1_text', models.CharField(max_length=255)),
                ('q1_options', models.JSONField(help_text="Format: ['Option1', 'Option2', 'Option3']")),
                ('q1_correct', models.IntegerField(help_text='Index 0-2')),
                ('q2_text', models.CharField(max_length=255)),
                ('q2_options', models.JSONField()),
                ('q2_correct', models.IntegerField()),
                ('q3_text', models.CharField(blank=True, help_text='Backup for failures', max_length=255, null=True)),
                ('q3_options', models.JSONField(blank=True, null=True)),
                ('q3_correct', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
