# Generated by Django 6.0.2 on 2026-03-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_listening', '0003_remove_listeninglesson_q1_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeninglesson',
            name='xp_reward',
            field=models.IntegerField(default=5),
        ),
    ]
