# Generated by Django 6.0.2 on 2026-03-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WritingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malayalam_meaning', models.CharField(max_length=500)),
                ('correct_sentence', models.CharField(max_length=500)),
                ('extra_words', models.CharField(blank=True, help_text="Comma separated words to confuse the user (e.g. 'is, are, was')", max_length=200, null=True)),
                ('level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('PROFESSIONAL', 'Professional')], max_length=20)),
            ],
        ),
    ]
