# Generated by Django 6.0.2 on 2026-03-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='xp_reward',
            field=models.IntegerField(default=5),
        ),
    ]
