# Generated by Django 6.0.2 on 2026-03-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_learning', '0002_chapter_xp_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('PROFESSIONAL', 'Professional')], default='BEGINNER', max_length=20),
        ),
    ]
