# Generated by Django 6.0.2 on 2026-03-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('PROFESSIONAL', 'Professional')], max_length=20)),
                ('story_content', models.TextField()),
                ('background_image_url', models.URLField()),
                ('q1_text', models.CharField(max_length=255)),
                ('q1_options', models.JSONField()),
                ('q1_correct', models.IntegerField()),
                ('q2_text', models.CharField(max_length=255)),
                ('q2_options', models.JSONField()),
                ('q2_correct', models.IntegerField()),
                ('q3_text', models.CharField(max_length=255)),
                ('q3_options', models.JSONField()),
                ('q3_correct', models.IntegerField()),
            ],
        ),
    ]
