# Generated by Django 6.0.2 on 2026-03-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_reading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingstory',
            name='q1_options',
        ),
        migrations.RemoveField(
            model_name='readingstory',
            name='q2_options',
        ),
        migrations.RemoveField(
            model_name='readingstory',
            name='q3_options',
        ),
        migrations.AddField(
            model_name='readingstory',
            name='q1_option_1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='readingstory',
            name='q1_option_2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='readingstory',
            name='q1_option_3',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='readingstory',
            name='q2_option_1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='readingstory',
            name='q2_option_2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='readingstory',
            name='q2_option_3',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='readingstory',
            name='q3_option_1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='readingstory',
            name='q3_option_2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='readingstory',
            name='q3_option_3',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='readingstory',
            name='q1_correct',
            field=models.IntegerField(choices=[(0, 'Option 1'), (1, 'Option 2'), (2, 'Option 3')], default=0),
        ),
        migrations.AlterField(
            model_name='readingstory',
            name='q2_correct',
            field=models.IntegerField(choices=[(0, 'Option 1'), (1, 'Option 2'), (2, 'Option 3')], default=0),
        ),
        migrations.AlterField(
            model_name='readingstory',
            name='q3_correct',
            field=models.IntegerField(choices=[(0, 'Option 1'), (1, 'Option 2'), (2, 'Option 3')], default=0),
        ),
    ]
