# Generated by Django 6.0.2 on 2026-03-04 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_reading', '0002_remove_readingstory_q1_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingstory',
            name='q1_correct',
        ),
        migrations.RemoveField(
            model_name='readingstory',
            name='q1_option_1',
        ),
        migrations.RemoveField(
            model_name='readingstory',
            name='q1_option_2',
        ),
        migrations.RemoveField(
            model_name='readingstory',
            name='q1_option_3',
        ),
        migrations.RemoveField(
            model_name='readingstory',
            name='q1_text',
        ),
        migrations.RemoveField(
            model_name='readingstory',
            name='q2_correct',
        ),
        migrations.RemoveField(
            model_name='readingstory',
            name='q2_option_1',
        ),
        migrations.RemoveField(
            model_name='readingstory',
            name='q2_option_2',
        ),
        migrations.RemoveField(
            model_name='readingstory',
            name='q2_option_3',
        ),
        migrations.RemoveField(
            model_name='readingstory',
            name='q2_text',
        ),
        migrations.RemoveField(
            model_name='readingstory',
            name='q3_correct',
        ),
        migrations.RemoveField(
            model_name='readingstory',
            name='q3_option_1',
        ),
        migrations.RemoveField(
            model_name='readingstory',
            name='q3_option_2',
        ),
        migrations.RemoveField(
            model_name='readingstory',
            name='q3_option_3',
        ),
        migrations.RemoveField(
            model_name='readingstory',
            name='q3_text',
        ),
        migrations.CreateModel(
            name='ReadingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('option_1', models.CharField(max_length=255)),
                ('option_2', models.CharField(max_length=255)),
                ('option_3', models.CharField(max_length=255)),
                ('correct', models.IntegerField(choices=[(0, 'Option 1'), (1, 'Option 2'), (2, 'Option 3')], default=0)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lessons_reading.readingstory')),
            ],
        ),
    ]
