# Generated by Django 6.0.2 on 2026-03-02 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('LISTENING', 'Listening'), ('SPEAKING', 'Speaking'), ('LEARNING', 'Learning'), ('READING', 'Reading'), ('WRITING', 'Writing')], max_length=20),
        ),
    ]
