# Generated by Django 6.0.2 on 2026-03-02 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0002_studentprofile_created_at_studentprofile_is_approved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('grammar_rule_malayalam', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ListeningLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('youtube_url', models.URLField()),
                ('level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('PROFESSIONAL', 'Professional')], max_length=20)),
                ('q1_text', models.CharField(max_length=255)),
                ('q1_options', models.JSONField(help_text="Format: ['Option1', 'Option2', 'Option3']")),
                ('q1_correct', models.IntegerField(help_text='Index of correct option (0, 1, or 2)')),
                ('q2_text', models.CharField(max_length=255)),
                ('q2_options', models.JSONField()),
                ('q2_correct', models.IntegerField()),
                ('q3_text', models.CharField(blank=True, help_text='Backup question for retries', max_length=255, null=True)),
                ('q3_options', models.JSONField(blank=True, null=True)),
                ('q3_correct', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('PROFESSIONAL', 'Professional')], max_length=20)),
                ('story_content', models.TextField(help_text='The full story text goes here')),
                ('background_image_url', models.URLField(help_text='Link to the story background image')),
                ('q1_text', models.CharField(max_length=255)),
                ('q1_options', models.JSONField(help_text='List of 4 strings')),
                ('q1_correct', models.IntegerField(help_text='Index 0-3')),
                ('q2_text', models.CharField(max_length=255)),
                ('q2_options', models.JSONField()),
                ('q2_correct', models.IntegerField()),
                ('q3_text', models.CharField(max_length=255)),
                ('q3_options', models.JSONField()),
                ('q3_correct', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WritingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malayalam_meaning', models.CharField(help_text='The hint shown to the student', max_length=500)),
                ('correct_sentence', models.CharField(help_text='The full correct English sentence', max_length=500)),
                ('level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('PROFESSIONAL', 'Professional')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='unlocked_chapter',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('call_type', models.CharField(choices=[('AI', 'Gemini AI'), ('FRIEND', 'Friend')], max_length=10)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('recording_file', models.FileField(blank=True, null=True, upload_to='recordings/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GrammarExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_text', models.CharField(max_length=500)),
                ('malayalam_explanation', models.CharField(max_length=500)),
                ('is_backup', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='core_api.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='GrammarQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('option_a', models.CharField(max_length=200)),
                ('option_b', models.CharField(max_length=200)),
                ('option_c', models.CharField(max_length=200)),
                ('option_d', models.CharField(max_length=200)),
                ('correct_option', models.IntegerField(help_text='Index 0-3 (0=A, 1=B, 2=C, 3=D)')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='core_api.chapter')),
            ],
        ),
    ]
