# Generated by Django 6.0.2 on 2026-03-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0003_chapter_listeninglesson_readingstory_writingtask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile_photos/default_user.png', null=True, upload_to='profile_photos/'),
        ),
    ]
