# Generated by Django 6.0.2 on 2026-03-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0004_studentprofile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammarquiz',
            name='correct_option',
            field=models.IntegerField(help_text='Index 0-3'),
        ),
        migrations.AlterField(
            model_name='listeninglesson',
            name='q1_correct',
            field=models.IntegerField(help_text='Index 0-2'),
        ),
        migrations.AlterField(
            model_name='listeninglesson',
            name='q3_text',
            field=models.CharField(blank=True, help_text='Backup for failures', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='readingstory',
            name='background_image_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='readingstory',
            name='q1_correct',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='readingstory',
            name='q1_options',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='readingstory',
            name='story_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='writingtask',
            name='correct_sentence',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='writingtask',
            name='malayalam_meaning',
            field=models.CharField(max_length=500),
        ),
    ]
