# Generated by Django 6.0.2 on 2026-03-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0005_alter_grammarquiz_correct_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='learning_xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='listening_xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='reading_xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='speaking_xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='writing_xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='writingtask',
            name='extra_words',
            field=models.CharField(blank=True, help_text="Comma separated words to confuse the user (e.g. 'is, are, was')", max_length=200, null=True),
        ),
    ]
