# Generated by Django 6.0.2 on 2026-03-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0006_studentprofile_learning_xp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='recording_file',
            field=models.FileField(default='recordings/manual_log.mp3', upload_to='recordings/'),
            preserve_default=False,
        ),
    ]
