# Generated by Django 6.0.2 on 2026-03-04 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0008_studentprofile_friends_studentprofile_is_dnd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calllog',
            name='student',
        ),
        migrations.RemoveField(
            model_name='grammarquiz',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='grammarexample',
            name='chapter',
        ),
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='to_user',
        ),
        migrations.DeleteModel(
            name='ListeningLesson',
        ),
        migrations.DeleteModel(
            name='ReadingStory',
        ),
        migrations.DeleteModel(
            name='WritingTask',
        ),
        migrations.DeleteModel(
            name='CallLog',
        ),
        migrations.DeleteModel(
            name='GrammarQuiz',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='GrammarExample',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
