# Generated by Django 6.0.2 on 2026-03-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0009_remove_calllog_student_remove_grammarquiz_chapter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalXPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_intermediate', models.IntegerField(default=1000)),
                ('overall_professional', models.IntegerField(default=5000)),
                ('section_intermediate', models.IntegerField(default=200)),
                ('section_professional', models.IntegerField(default=1000)),
                ('points_per_activity', models.IntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
