# Generated by Django 6.0.2 on 2026-03-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0010_globalxpconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='xp_earned',
            field=models.IntegerField(default=0, help_text='Specific XP earned for this activity'),
        ),
    ]
