# Generated by Django 6.0.2 on 2026-03-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0011_activitylog_xp_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalxpconfig',
            name='learning_default_xp',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='globalxpconfig',
            name='listening_beginner_xp',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='globalxpconfig',
            name='listening_intermediate_xp',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='globalxpconfig',
            name='listening_professional_xp',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='globalxpconfig',
            name='reading_beginner_xp',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='globalxpconfig',
            name='reading_intermediate_xp',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='globalxpconfig',
            name='reading_professional_xp',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='globalxpconfig',
            name='speaking_beginner_xp',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='globalxpconfig',
            name='speaking_intermediate_xp',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='globalxpconfig',
            name='speaking_professional_xp',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='globalxpconfig',
            name='writing_beginner_xp',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='globalxpconfig',
            name='writing_intermediate_xp',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='globalxpconfig',
            name='writing_professional_xp',
            field=models.IntegerField(default=15),
        ),
    ]
