# Generated by Django 6.0.2 on 2026-03-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0012_globalxpconfig_learning_default_xp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalxpconfig',
            old_name='learning_default_xp',
            new_name='learning_intermediate_xp',
        ),
        migrations.AddField(
            model_name='globalxpconfig',
            name='learning_beginner_xp',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='globalxpconfig',
            name='learning_professional_xp',
            field=models.IntegerField(default=15),
        ),
    ]
