# Generated by Django 6.0.2 on 2026-03-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0013_rename_learning_default_xp_globalxpconfig_learning_intermediate_xp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='item_id',
            field=models.IntegerField(blank=True, help_text='ID of the lesson/chapter/story', null=True),
        ),
    ]
